### ISSUE TITLE
Creating DAE files with embedded textures

### ISSUE THREAD

**Issue by JakubKahovec** [dmsurti/AssimpKit#57]
Hi @dmsurti ,

may I ask how did you manage to create DAE files, in your example app, which have  embedded textures ? I tried Blender 2.78 but it always put them aside, and I'm not even able to read them in AssimpKit. Yours DAE files work fine though.

Thank you.

**Comment by dmsurti** [comment]
@JakubKahovec I did not create any of these DAE files used in the example app; they come from various sources namely:

- Files in `assimp`
- Files from `openframeworks`
- Files from `apple` examples

What platform are you using AssimpKit on? iOS or macOS.

Your issue could be related to the fact that AssimpKit assumes the texture files are placed along side the source file, the dae files in your case. See: https://github.com/dmsurti/AssimpKit/blob/master/AssimpKit/Code/Model/AssimpImporter.m#L595

So even if Blender puts aside the texture files, as long as you can place the dae file, texture files alongside in one directory, then AssimpKit should be able to read those fine. Otherwise, can you send me a sample of the DAE file which does not get imported with `AssimpKit` and I could look into it?

Thanks.

**Comment by JakubKahovec** [comment]
Thank you for your quick response. I'm using AssimpKit on iOS.  
[Table.zip](https://github.com/dmsurti/AssimpKit/files/1217597/Table.zip)
I'm attaching the exported files.

**Comment by dmsurti** [comment]
@JakubKahovec Thanks for the files. I will check it over the weekend and let you know.

**Comment by dmsurti** [comment]
@JakubKahovec AssimpKit fails with the following error:

```
2017-08-14 23:12:42.558685+0530 OSX-Example[20693:1606676] -[AssimpImporter importScene:postProcessFlags:] [Line 137]  Scene importing failed for filePath /Users/deepaksurti/Downloads/Table/Wood_Table.dae
2017-08-14 23:12:42.558711+0530 OSX-Example[20693:1606676] -[AssimpImporter importScene:postProcessFlags:] [Line 138]  Scene importing failed with error Collada: Unable to resolve effect texture entry "**table_Col_png-sampler**", ended up at ID "**table_Col_png**".
```

A quick look at your `.dae` file in a text editor refers to this:

```
            <diffuse>
              <texture texture="table_Col_png-sampler" texcoord="UVMap.001"/>
            </diffuse>
```

I think your diffuse texture may be missing when you export your asset from Blender. Sorry, but I don't have a detailed idea of how Collada exporter of Blender works, but check out their settings and ensure that whatever textures you have used in your blender scene are all exported. 

--

By the way, I just checked with the SceneKit editor and a sample app, as SceneKit directly supports Collada and you don't need any other library TBH. SceneKit's collada importer is more lenient as it just renders the table without any textures applied, which shows that there is a problem with the way Blender has exported the dae file and the textures. AssimpKit (with `assimp`) is not so forgiving :-(

I have attached a sample SceneKit project for this asset 
[TableSceneKit.zip](https://github.com/dmsurti/AssimpKit/files/1223009/TableSceneKit.zip). Check out this screenshot.

<img width="627" alt="screenshot 2017-08-14 23 24 57" src="https://user-images.githubusercontent.com/4158417/29284363-002373fc-8148-11e7-88fb-3441ed4861d3.png">

Please try with a new export with the dae file and all textures in place, if you still need to use `AssimpKit`.

Hope this helps. Thanks :-)

**Comment by JakubKahovec** [comment]
@dmsurti thank you for such thorough analysis. I've concluded pretty much the same. When exporting though  I tried several options but I was not able to export it in such a way it would work. I also tried other tools like Cinema 4D or SketchUp but with none of them I was able to export it so that it loadable with texturess in  AssimpKit. Without textures it works pretty good, but the only models where textures work corretly are the ones which you have part of your iOS example. Do you have an experience with some tool which would export models into Collada DAE format and textures would load correctly with Assimkit ?

**Comment by dmsurti** [comment]
@JakubKahovec I found a .dae file with a 3D model of a wooden create and specular, diffuse and normal textures. I exported it from Blender with the following settings:

<img width="355" alt="screenshot 2017-08-17 20 43 25" src="https://user-images.githubusercontent.com/4158417/29419632-38bc2370-838d-11e7-80a5-ce70be436853.png">

Note that I check the options to Include textures and also the Copy option, so that the texture files are copied to the destination where you place your exported `.dae` file.

Then I exported this model in AssimpKit and checked with both MacOS and iOS example viewers:

<img width="912" alt="screenshot 2017-08-17 20 36 47" src="https://user-images.githubusercontent.com/4158417/29419690-5f556bc2-838d-11e7-844d-6507077f4560.png">

<img width="890" alt="screenshot 2017-08-17 20 41 05" src="https://user-images.githubusercontent.com/4158417/29419691-60563a4c-838d-11e7-99ad-058aaded6cfd.png">

PS: The blend file I used for testing this is proprietary and hence I cannot share it, Sorry!

I hope the above instructions can help you further. So I would suggest you try exporting from Blender correctly and then if AssimpKit does not work, open this issue again. I am closing it for now.
